spring.application.name=tool
spring.datasource.url=jdbc:postgresql://localhost:5432/redteam_db
spring.datasource.username=postgres
spring.datasource.password=sandhya

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
server.port=8081